In [1]:
import numpy as np

In [8]:
A = np.array([[1,2,3],[4,9,6],[2,2,8]])
print(A.shape)
A

(3, 3)


array([[1, 2, 3],
       [4, 9, 6],
       [2, 2, 8]])

In [16]:
np.argpartition(A,1,axis=0)

array([[0, 0, 0],
       [2, 2, 1],
       [1, 1, 2]])

In [18]:
np.argpartition(A,1,axis=1)

array([[0, 1, 2],
       [0, 2, 1],
       [0, 1, 2]])

In [22]:
A.argsort()

array([[0, 1, 2],
       [0, 2, 1],
       [0, 1, 2]])

In [24]:
np.argpartition(A.ravel(), 3)
np.un

array([0, 6, 1, 7, 2, 5, 3, 8, 4])